// ABOUTME: Placeholder exercise data standing in for the FastAPI exercises endpoints, which
// ABOUTME: don't exist yet — replace with a real fetch once the backend lands.

import type { AdminExercise } from "@/types";

export const ADMIN_EXERCISES: AdminExercise[] = [
  {
    id: "exercise-home-breathing-reset",
    title: "Breathing Reset",
    description: "A short breathing exercise to help you settle.",
    subtitle: null,
    type: "Breathing",
    category: null,
    durationMinutes: 3.5,
    audioUrl: "https://cdn.example.com/audio/breathing-reset.mp3",
    displayOrder: 0,
    showOnHomeScreen: true,
    isActive: true,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: "exercise-home-grounding",
    title: "Grounding Meditation",
    description: "Reconnect with the present moment.",
    subtitle: null,
    type: "Meditation",
    category: null,
    durationMinutes: 5,
    audioUrl: "https://cdn.example.com/audio/grounding.mp3",
    displayOrder: 1,
    showOnHomeScreen: true,
    isActive: true,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: "exercise-anxiety-calming-breath",
    title: "Calming Breath",
    description: "A gentle breathing pattern to ease anxious moments.",
    subtitle: "For racing thoughts",
    type: "Breathing",
    category: "Anxiety",
    durationMinutes: 4,
    audioUrl: "https://cdn.example.com/audio/calming-breath.mp3",
    displayOrder: 0,
    showOnHomeScreen: false,
    isActive: true,
    createdAt: "2026-06-05T09:00:00.000Z",
    updatedAt: "2026-07-18T09:00:00.000Z",
  },
  {
    id: "exercise-anxiety-body-scan",
    title: "Body Scan",
    description: "A slow scan through the body to release tension.",
    subtitle: null,
    type: "Meditation",
    category: "Anxiety",
    durationMinutes: 8,
    audioUrl: null,
    displayOrder: 1,
    showOnHomeScreen: false,
    isActive: false,
    createdAt: "2026-06-10T09:00:00.000Z",
    updatedAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "exercise-boundaries-visualize",
    title: "Visualize Your Boundary",
    description: "A visualization exercise for holding a boundary with confidence.",
    subtitle: null,
    type: "Visualization",
    category: "Boundaries",
    durationMinutes: 6,
    audioUrl: "https://cdn.example.com/audio/visualize-boundary.mp3",
    displayOrder: 0,
    showOnHomeScreen: false,
    isActive: true,
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "exercise-burnout-reset",
    title: "Burnout Reset",
    description: "A short practice to recover energy mid-day.",
    subtitle: null,
    type: "Breathing",
    category: "Burnout",
    durationMinutes: 3,
    audioUrl: "https://cdn.example.com/audio/burnout-reset.mp3",
    displayOrder: 0,
    showOnHomeScreen: false,
    isActive: true,
    createdAt: "2026-07-15T09:00:00.000Z",
    updatedAt: "2026-07-15T09:00:00.000Z",
  },
];

export function getExerciseById(id: string): AdminExercise | undefined {
  return ADMIN_EXERCISES.find((exercise) => exercise.id === id);
}
